fix undefined reference to glViewport
x86_64-pc-linux-gnu-c++  -march=native -pipe -O3 -gdwarf-4 -fvar-tracking-assignments -grecord-gcc-switches -L../../src -L/usr/lib -pthread -lSDL2  -lGLEW -lGLU -lOSMesa  -lBulletSoftBody -lBulletDynamics -lBulletCollision -lLinearMath  -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -o demo demo-main.o demo-camera.o demo-window.o demo-graphics.o -ltdse -lboost_system-mt
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: demo-graphics.o: undefined reference to symbol 'glViewport'
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: /usr/host/lib/libGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status